# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # The correct version of pytest-homeassistant-custom-component is selected by pip to match the version of Home Assistant, the minimum version is there because some old versions of pytest-homeassistant-custom-component did not pin the Home Assistant version
      - dependency-name: "pytest-homeassistant-custom-component"
      # Dependabot should not update Home Assistant as that should match the homeassistant key in hacs.json
      - dependency-name: "homeassistant"
      # The following dependencies should match the version specified in manifest.json of this integration
      # (but we want to receive a notification from dependabot, so they stay commented out)
      # - dependency-name: "telegramify-markdown[mermaid]"
      # - dependency-name: "pyogg"
      # The following dependencies should match the versions used in Home Assistant
      - dependency-name: "python-telegram-bot[socks]"
      - dependency-name: "aiofiles"
      - dependency-name: "colorlog"
      - dependency-name: "hassil"
      - dependency-name: "PyTurboJPEG"
      - dependency-name: "mutagen"
      - dependency-name: "ha-ffmpeg"
    cooldown:
      default-days: 7
