name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ha-version == 'dev' }}
    strategy:
      fail-fast: false
      matrix:
        ha-version: ["hacs", "latest", "dev"]
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/python.json"
          echo "::add-matcher::.github/workflows/matchers/pytest-slow.json"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0

      - name: Install requirements
        run: scripts/bootstrap
        env:
          HA_VERSION: ${{ matrix.ha-version }}

      - name: Pytest
        run: pytest --cov custom_components/telegram_bot_conversation --cov-report=term-missing $(test "$RUNNER_DEBUG" && echo "-vv")

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@ac868b9540fad490f7ca82b8ca00480fd751ed19 # develop, not tagged
        with:
          parallel: true
          flag-name: ${{ matrix.ha-version }}.${{ matrix.python-version }}
          debug: ${{ runner.debug && 'true' || 'false' }}

  coverage:
    name: Coverage
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Coverage
        uses: AndreMiras/coveralls-python-action@ac868b9540fad490f7ca82b8ca00480fd751ed19 # develop, not tagged
        with:
          parallel-finished: true
          debug: ${{ runner.debug && 'true' || 'false' }}
